DROP DATABASE IF EXISTS ShopManager;
CREATE DATABASE ShopManager;
USE ShopManager;

CREATE TABLE Town (
    TownId INT AUTO_INCREMENT PRIMARY KEY,
    TownName VARCHAR(50) NOT NULL
);

CREATE TABLE Shop (
    ShopId INT AUTO_INCREMENT PRIMARY KEY,
    ShopNickName VARCHAR (50) NOT NULL,
    Fk_Town INT NOT NULL,
    FOREIGN KEY (Fk_Town) REFERENCES Town(TownId)
);

CREATE TABLE Department (
    DepartmentId INT AUTO_INCREMENT PRIMARY KEY,
    DepartmentName VARCHAR (50)
);
